parse_config:
  # Needed so the parser finds "zmk-helpers/helper.h"
  zmk_additional_includes: ["zmk-helpers/include"]

  # Readable legends instead of raw behavior names
  raw_binding_map:
    "&ae_mac": "ä Ä"
    "&oe_mac": "ö Ö"
    "&ue_mac": "ü Ü"
    "&ae_win": "ä Ä (Win)"
    "&oe_win": "ö Ö (Win)"
    "&ue_win": "ü Ü (Win)"
    "&ae_lnx": "ä Ä (Lnx)"
    "&oe_lnx": "ö Ö (Lnx)"
    "&ue_lnx": "ü Ü (Lnx)"
    "&mac_ae_lo": "ä"
    "&mac_oe_lo": "ö"
    "&mac_ue_lo": "ü"
    "&mac_ae_up": "Ä"
    "&mac_oe_up": "Ö"
    "&mac_ue_up": "Ü"
    "&win_ae_lo": "ä"
    "&win_oe_lo": "ö"
    "&win_ue_lo": "ü"
    "&win_ae_up": "Ä"
    "&win_oe_up": "Ö"
    "&win_ue_up": "Ü"
    "&win_eszett": "ß"
    "&win_euro": "€"
    "&win_sleep": "Sleep"
    "&lnx_ae_lo": "ä"
    "&lnx_oe_lo": "ö"
    "&lnx_ue_lo": "ü"
    "&lnx_ae_up": "Ä"
    "&lnx_oe_up": "Ö"
    "&lnx_ue_up": "Ü"
    "&lnx_eszett": "ß"
    "&lnx_euro": "€"
    "&kp LA(S)": "ß"
    "&kp LA(LS(N2))": "€"
    "&kp LG(LEFT)": "Line start"
    "&kp LG(RIGHT)": "Line end"
    "&kp LA(LEFT)": "Word ←"
    "&kp LA(RIGHT)": "Word →"
    "&kp LC(LEFT)": "Word ←"
    "&kp LC(RIGHT)": "Word →"
    "&kp LC(LG(Q))": "Lock"
    "&kp LG(L)": "Lock"
    "&kp LC(LA(LG(N4)))": "Screenshot"
    "&caps_word": "Caps Word"
    "&to 0": "Mode: Mac"
    "&to 1": "Mode: Win"
    "&to 2": "Mode: Linux"

draw_config:
  dark_mode: auto
